[workspace]

members = [
    "cli",
    "codegen",
    "common",
    "compiler",
    "db",
    "diagnostics",
    "lexer",
    "lsp",
    "parser",
    "session",
    "syntax",
    "types",
    "vfs"
]